copy appdr2\*.*   		\dev\allcode\*.*
copy coregame\*.* 		\dev\allcode\*.*
copy coregame_ai\*.* 		\dev\allcode\*.*
copy coregame_interface\*.* 	\dev\allcode\*.*
copy coregame_orders\*.* 	\dev\allcode\*.*
copy coregame_objects\*.* 	\dev\allcode\*.*
copy coregame_particles\*.* 	\dev\allcode\*.*
copy coregame_tasks\*.* 	\dev\allcode\*.*
copy game\*.* 			\dev\allcode\*.*
copy graphics\*.* 		\dev\allcode\*.*
copy interface\*.* 		\dev\allcode\*.*
copy main\*.* 			\dev\allcode\*.*
copy multiplayer\*.* 		\dev\allcode\*.*
copy sound\*.* 			\dev\allcode\*.*
copy system\*.* 		\dev\allcode\*.*
copy util\*.* 			\dev\allcode\*.*